<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Task Management System API
 *
 * API for managing Projects and Tasks.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for projectsGet
     *
     * Getting Projects list.
     *
     */
    public function testProjectsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsIdDelete
     *
     * Deleting Project.
     *
     */
    public function testProjectsIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsIdGet
     *
     * Getting information about certain project.
     *
     */
    public function testProjectsIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsIdPut
     *
     * Update Project Information.
     *
     */
    public function testProjectsIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsPost
     *
     * New Project creation.
     *
     */
    public function testProjectsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsProjectIdTasksGet
     *
     * Getting Tasks list for Project.
     *
     */
    public function testProjectsProjectIdTasksGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsProjectIdTasksIdDelete
     *
     * Delete task.
     *
     */
    public function testProjectsProjectIdTasksIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsProjectIdTasksIdGet
     *
     * Getting information about certain Task.
     *
     */
    public function testProjectsProjectIdTasksIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsProjectIdTasksIdPut
     *
     * Update Task Information.
     *
     */
    public function testProjectsProjectIdTasksIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectsProjectIdTasksPost
     *
     * New Task creation.
     *
     */
    public function testProjectsProjectIdTasksPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
